



var Qlist_0_00 = [
    "甘草芭樂",
    "咖哩飯",
    "蜘蛛人",
    "咖啡牛奶",
    "香蒜麵包",
    "法式吐司",
    "人生勝利組",
    "任意門",
    "隱型斗篷",
    "健達出奇蛋",
    "一見鍾情",
    "番茄",
    "胡椒餅",
    "抹茶巧克力",
    "薄荷巧克力",
    "龍舌蘭",
    "菜雞",
    "泡牛奶",
    "烤餅乾",
    "簽字筆",
    "下午茶",
    "漢堡肉",
    "豪大大雞排",
];

var Qlist_0_01 = [
    "公民凱恩<span>Citizen Kane, 1941</span>",
    "教父<span>The Godfather, 1972</span>",
    "卡薩布蘭卡<span>Casablanca, 1942</span>",
    "亂世佳人<span>Gone with the Wind, 1939</span>",
    "阿拉伯的勞倫斯<span>Lawrence of Arabia, 1962</span>",
    "綠野仙蹤<span>The Wizard of Oz, 1939</span>",
    "畢業生<span>The Graduate, 1967</span>",
    "碼頭風雲<span>On the Waterfront, 1954</span>",
    "辛德勒的名單<span>Schindler's List, 1993</span>",
    "雨中曲<span>Singin' in the Rain, 1952</span>",
    "生活多美好<span>It's a Wonderful Life, 1946</span>",
    "日落大道<span>Sunset Boulevard, 1950</span>",
    "桂河大橋<span>The Bridge on the River Kwai, 1957</span>",
    "熱情似火<span>Some Like It Hot, 1959</span>",
    "星球大戰<span>Star Wars, 1977</span>",
    "彗星美人<span>All About Eve, 1950</span>",
    "非洲女王號<span>The African Queen, 1951</span>",
    "驚魂記<span>Psycho, 1960</span>",
    "唐人街<span>Chinatown, 1974</span>",
    "飛越瘋人院<span>One Flew Over the Cuckoo's Nest, 1975</span>",
    "憤怒的葡萄<span>The Grapes of Wrath, 1940</span>",
    "2001太空漫遊<span>2001: A Space Odyssey, 1968</span>",
    "馬耳他之鷹<span>The Maltese Falcon, 1941</span>",
    "憤怒的公牛<span>Raging Bull, 1980</span>",
    "外星人E.T.<span>E.T. THE EXTRA-TERRESTRIAL, 1982</span>",
    "奇愛博士<span>Dr. Strangelove, 1964</span>",
    "雌雄大盜<span>Bonnie and Clyde, 1967</span>",
    "現代啓示錄<span>Apocalypse Now, 1979</span>",
    "史密斯先生到華盛頓<span>Mr. Smith Goes to Washington, 1939</span>",
    "浴血金沙<span>The Treasure of the Sierra Madre, 1948</span>",
    "安妮·霍爾<span>Annie Hall, 1977</span>",
    "教父2<span>The Godfather Part II, 1974</span>",
    "正午<span>High Noon, 1952</span>",
    "殺死一隻知更鳥<span>To Kill a Mockingbird, 1962</span>",
    "一夜風流<span>It Happened One Night, 1934</span>",
    "午夜牛郎<span>Midnight Cowboy, 1969</span>",
    "黃金時代<span>The Best Years of Our Lives, 1946</span>",
    "雙重賠償<span>Double Indemnity, 1944</span>",
    "日瓦戈醫生<span>Doctor Zhivago, 1965</span>",
    "西北偏北<span>North by Northwest, 1959</span>",
    "西區故事<span>West Side Story, 1961</span>",
    "後窗<span>Rear Window, 1954</span>",
    "金剛<span>King Kong, 1933</span>",
    "一個國家的誕生<span>The Birth of a Nation, 1915</span>",
    "慾望號街車<span>A Streetcar Named Desire, 1951</span>",
    "發條橙<span>A Clockwork Orange, 1971</span>",
    "出租車司機<span>Taxi Driver, 1976</span>",
    "大白鯊<span>Jaws, 1975</span>",
    "白雪公主和七個小矮人<span>Snow White and the Seven Dwarfs, 1937</span>",
    "虎豹小霸王<span>Butch Cassidy and the Sundance Kid, 1969</span>",
    "費城故事<span>The Philadelphia Story, 1940</span>",
    "亂世忠魂<span>From Here to Eternity, 1953</span>",
    "莫扎特傳<span>Amadeus, 1984</span>",
    "西線無戰事<span>All Quiet on the Western Front, 1930</span>",
    "音樂之聲<span>The Sound of Music, 1965</span>",
    "陸軍野戰醫院<span>M*A*S*H, 1970</span>",
    "第三人<span>The Third Man, 1949</span>",
    "幻想曲<span>Fantasia, 1940</span>",
    "無因的反叛<span>Raiders of the Lost Ark, 1955</span>",
    "奪寶奇兵<span>Rebel Without a Cause, 1981</span>",
    "迷魂記<span>Vertigo, 1958</span>",
    "窈窕淑男<span>Tootsie, 1982</span>",
    "關山飛渡<span>Stagecoach, 1939</span>",
    "第三類接觸<span>Close Encounters of the Third Kind, 1977</span>",
    "沉默的羔羊<span>The Silence of the Lambs, 1991</span>",
    "電視台風雲<span>Network, 1976</span>",
    "諜網迷魂<span>The Manchurian Candidate, 1962</span>",
    "一個美國人在巴黎<span>An American in Paris, 1951</span>",
    "原野奇俠<span>Shane, 1953</span>",
    "法國販毒網<span>The French Connection, 1971</span>",
    "阿甘正傳<span>Forrest Gump, 1994</span>",
    "賓虛<span>Ben-Hur, 1959</span>",
    "呼嘯山莊<span>Wuthering Heights, 1939</span>",
    "淘金記<span>The Gold Rush, 1925</span>",
    "與狼共舞<span>Dances with Wolves, 1990</span>",
    "城市之光<span>City Lights, 1931</span>",
    "美國風情畫<span>American Graffiti, 1973</span>",
    "洛奇<span>Rocky, 1976</span>",
    "獵鹿人<span>The Deer Hunter, 1978</span>",
    "日落黃沙<span>The Wild Bunch, 1973</span>",
    "摩登時代<span>Modern Times, 1936</span>",
    "巨人傳<span>Giant, 1956</span>",
    "野戰排<span>Platoon, 1986</span>",
    "冰血暴<span>Fargo, 1996</span>",
    "鴨羹<span>Duck Soup, 1933</span>",
    "叛艦喋血記<span>Mutiny on the Bounty, 1935</span>",
    "科學怪人<span>Frankenstein, 1931</span>",
    "逍遙騎士<span>Easy Rider, 1969</span>",
    "巴頓將軍<span>Patton, 1970</span>",
    "爵士歌王<span>The Jazz Singer, 1927</span>",
    "窈窕淑女<span>My Fair Lady, 1964</span>",
    "郎心如鐵<span>A Place in the Sun, 1951</span>",
    "桃色公寓<span>The Apartment, 1960</span>",
    "好傢伙<span>Goodfellas, 1990</span>",
    "低俗小説<span>Pulp Fiction, 1994</span>",
    "搜索者<span>The Searchers, 1956</span>",
    "育嬰奇譚<span>Bringing Up Baby, 1938</span>",
    "不可饒恕<span>Unforgiven, 1992</span>",
    "猜猜誰來吃晚餐<span>Guess Who's Coming to Dinner, 1967</span>",
    "勝利之歌<span>Yankee Doodle Dandy, 1942</span>",
];

var Qlist_0_02 = [
    "滷肉飯<span>Braised pork rice  </span>",
    "牛肉麵<span>Beef noodles   </span>",
    "蚵仔煎<span>Oyster omelet   </span>",
    "珍珠奶茶<span>Bubble tea   </span>",
    "虱目魚<span>Milkfish    </span>",
    "擔仔麵<span>Slack Season danzai noodles </span>",
    "生煎包<span>Pan-fried buns   </span>",
    "割包、刈包<span>Gua bao   </span>",
    "鐵蛋Iron<span>egg    </span>",
    "鳳梨酥<span>Pineapple cake   </span>",
    "甜不辣<span> Tian bu la (Taiwanese</span>",
    "肉圓<span>Ba wan (Giant meat dumplings)</span>",
    "炸雞<span>Fried chicken   </span>",
    "蔥抓餅Flaky<span>scallion pancakes   </span>",
    "蚵仔麵線<span>Oyster vermicelli   </span>",
    "臭豆腐<span>Stinky tofu   </span>",
    "油豆腐<span>Oily bean curd  </span>",
    "豆干<span>Dried tofu   </span>",
    "蕃薯<span>Sweet potato   </span>",
    "剉冰<span>Shaved ice mountain  </span>",
    "胡椒餅<span>Pepper cakes   </span>",
    "小籠包<span>Dumplings    </span>",
    "魚丸湯<span>Fish ball soup  </span>",
    "藥燉排骨<span>Ribs stewed in medicinal herbs</span>",
    "鵝肉<span> Goose   </span>",
    "鼎邊銼<span> Ding bian cuo </span>",
    "麻糬<span>Mochi    </span>",
    "加熱滷味<span>Anything braised with Lantern soy</span>",
    "筒仔米糕<span>Tube rice pudding  </span>",
    "台式早餐（豆漿油條）<span>Taiwanesebreakfast</span>",
    "豬血湯<span>Pig’s blood rice pudding </span>",
    "三杯雞<span>Three-cup chicken   </span>",
    "粄條<span>Ban tiao noodles  </span>",
    "洪瑞珍三明治<span>Horng Ryen Jen Sandwich </span>",
    "愛玉<span>Aiyu jelly   </span>",
    "皮蛋豆腐<span>Pidan tofu   </span>",
    "潤餅<span>Taiwan burrito   </span>",
    "麻辣火鍋<span>Spicy hotpot   </span>",
    "雞翅飯捲<span>Chicken wing rice roll </span>",
    "貢丸湯<span>Pork balls soup  </span>",
    "便當<span>Biandang    </span>",
    "大腸包小腸<span>Doubled layer roll (sausage) </span>",
    "肉粽<span>    </span>",
    "肉羹麵<span>    </span>",
    "車輪餅<span>    </span>",
    "草仔粿<span>    </span>",
    "碗粿<span>Salty rice pudding  </span>",
    "豬血糕<span>Pigs blood cake  </span>",
    "雞排<span>    </span>",
    "竹筒飯<span>Tube-shaped container rice  </span>",
    "發粿<span>Rice cake   </span>",
    "芒果冰<span>Mango milk shaved ice </span>",
    "燒仙草<span>Boiled Grass Jelly  </span>",
    "綠豆湯<span>mung bean  soup </span>",
    "紅豆湯<span>red bean soup  </span>",
    "酸梅湯<span>sour prune juice  </span>",
    "芋圓<span>taro balls   </span>",
    "豆花<span>tofu pudding   </span>",
    "粉圓冰<span>powder circle ice  </span>",
    "客家擂茶<span>Hakka Lei tea  </span>",
    "木瓜牛奶<span> papaya smoothie  </span>",
    "米漿<span>peanut rice milk  </span>",
    "鍋貼<span>pot stickers   </span>",
    "蘿蔔糕<span>radish cake   </span>",
    "水餃<span>dumpling    </span>",
    "蒸餃<span>Steamed dumplings   </span>",
    "炒米粉<span>Fried rice noodles  </span>",
    "魷魚羹<span>Squid Potage   </span>",
    "油飯<span>Glutinous oil rice  </span>",
    "蔥油餅<span>Flaky scallion pancakes  </span>",
    "蛋花湯<span>egg drop soup  </span>",
    "花生湯<span>peanut soup   </span>",
    "米粉湯<span>Rice Noodle Soup  </span>",
    "餛飩湯<span>wonton soup   </span>",
    "當歸羊肉<span>    </span>",
    "卜肉<span>    </span>",
    "黑胡椒鐵板麵<span>    </span>",
    "麻辣鴨血臭豆腐<span>    </span>",
    "煎餃<span>    </span>",
    "飯糰<span>Rice roll   </span>",
    "炒麵<span>    </span>",
    "餛飩麵<span>Wonton & noodles  </span>",
    "刀削麵<span>Sliced noodles   </span>",
    "麻醬麵<span>Sesame paste noodles  </span>",
    "鴨肉麵<span>Duck with noodles  </span>",
    "鵝肉麵<span>Goose with noodles  </span>",
    "榨菜肉絲麵<span>Pork, pickled mustard green noodles</span>",
    "鍋燒意麵<span>    </span>",
    "鹹粥<span>    </span>",
    "肉燥飯<span>    </span>",
    "鹹酥雞<span>    </span>",
    "炒泡麵<span>    </span>",
    "四神湯<span>    </span>",
    "阿給<span>    </span>",
    "蛋炒飯<span>    </span>",
    "蚵嗲<span>    </span>",
    "鹹水雞<span>    </span>",
    "炸鮮奶<span>    </span>",
    "炸熱狗<span>    </span>",
    "牛舌餅<span>    </span>",
    "羊肉爐<span>    </span>",
    "豬腳<span>    </span>",
    "泡泡冰<span>Shaved ice   </span>",
    "綿綿冰<span>Mein mein ice  </span>",
    "客家小炒<span>    </span>",
    "火雞肉飯<span>    </span>",
    "花生糖<span>    </span>",
    "剝皮辣椒<span>    </span>",
    "蜜餞<span>    </span>",
    "拔絲地瓜<span>    </span>",
    "虱目魚粥<span>    </span>",
    "古早味蛋餅<span>    </span>",
    "涼麵<span>    </span>",
    "麵線糊<span>    </span>",
    "台南蝦仁飯<span>    </span>",
    "台式可麗餅<span>    </span>",
    "櫻花蝦米糕<span>    </span>",
    "古早味蛋糕<span>    </span>",
    "地瓜球<span>    </span>",
    "黑白切<span>    </span>",
    "米苔目<span>    </span>",
    "肉包<span>    </span>",
    "白糖粿<span>    </span>",
    "芋粿巧<span>    </span>",
    "小捲米粉<span>    </span>",
    "台式馬卡龍<span>    </span>",
    "土魠魚羹<span>    </span>",
    "豬油拌飯<span>    </span>",
    "珍珠奶茶<span>    </span>",
    "棺材板<span>Coffin bread   </span>",
    "鱔魚麵<span>Eel noodles   </span>",
    "蔥抓餅<span>    </span>",
    "烤魷魚<span>    </span>",
    "烤玉米<span>    </span>",
    "雞蛋糕<span>    </span>",
    "天婦羅<span>Tempura    </span>",
    "蝦球<span>Shrimp balls   </span>",
    "春捲<span>Spring rolls   </span>",
    "雞捲<span>Chicken rolls   </span>",
    "烤香腸<span>    </span>",
    "冰火湯圓<span>    </span>",
    "甘蔗汁<span>Sugar cane juice  </span>",
    "酸梅汁<span>Plum juice   </span>",
    "楊桃汁<span>Star fruit juice  </span>",
    "青草茶<span>Herb juice   </span>",
    "皮蛋<span>100-year egg   </span>",
    "鐵蛋<span>1000-year egg   </span>",
    "茶葉蛋<span>Tea egg   </span>",
    "滷蛋<span>Hard boiled egg  </span>",
    "鹹鴨蛋<span>Salted duck egg  </span>",
    "燒餅<span>Clay oven rolls  </span>",
    "油條<span>Fried bread stick  </span>",
    "韭菜盒<span>Fried leek dumplings  </span>",
    "饅頭<span>Steamed buns   </span>",
    "糖葫蘆<span>Tomatoes on sticks  </span>",
    "壽桃<span>Longevity Peaches   </span>",
    "芝麻球<span>Glutinous rice sesame balls </span>",
    "麻花<span>Fried dough twist  </span>",
    "雙胞胎<span>Horse hooves   </span>",
];


var Qlist_0_03 = [
    "仁醫",
    "機器女友Q10",
    "告白",
    "MR.Brain腦科學先生",
    "咩妹的完美執事",
    "篤姬",
    "BLOODY MONDAY",
    "Last Friends",
    "流星之絆",
    "戀空",
    "求婚大作戰",
    "魚干女又怎樣",
    "花樣少年少女",
    "貧窮貴公子",
    "空中急診英雄",
    "死亡筆記本",
    "14歲小媽媽",
    "交響情人夢",
    "我的老大，我的英雄",
    "女王的教室",
    "流星花園",
    "改造野豬妹",
    "東大特訓班",
    "一公升的眼淚",
    "Orange Days",
    "白色巨塔",
    "夏之雪",
    "池袋西口公園",
    "大和拜金女",
    "To Heart至死不渝的愛",
    "魔女的條件",
    "孩子們的戰爭",
    "長假",
    "惡作劇之吻",
    "情書",
    "無家可歸的小孩",
    "東京愛情故事",
];
var Qlist_0_04 = [
    "CIC ROOM",
    "KVM Switch",
    "PDU",
    "VK2100",
    "Power Distribution & Rack Solutions",
    "Professional Audio/Video",
    "Control System",
    "4-Port Serial Expansion Box",
    "Seamless Switch",
    "Presentation switch",
    "Video matrix switch",
    "Room Booking System",
    "DisplayPort HDBaseT-Lite Receiver",
    "HDMI over IP ",
    "4K",
];













var Qlist_1_01 = [
    "如果看到金城武熟睡在自己面前，你會做什麼?",
    "你最近都聽什麼哥?",
    "當你不知道要穿什麼顏色的衣服時，你會選什麼顏色?",
    "去年你最後悔的一件事是什麼?",
    "哪天你變身蜘蛛人，第一件事會做什麼?",
    "你昨天吃什麼當晚餐?",
    "你曾遇過最感動的事情是什麼?",
    "如果你有一張單程機票，你會去哪?",
    "你覺得人生勝利組是要具備什麼條件?",
    "如果你有任意門，你想去哪?",
    "如果你有隱型斗篷，你會怎麼做?",
    "如果你想重來，你會回到哪個時期?",
    "你相信一見鍾情嗎?",
    "你相信男女間有純友誼嗎?",
    "要對10年後的自己說一句話，你會說什麼?",
    "你最討厭的動物是什麼?",
    "你在Uber上發現沒帶錢包也沒帶手機，怎麼辦?",
    "如果你中10萬塊樂透，你要幹嘛?",
    "最近買過最貴的物品是什麼?",
    "上一次去台北101，是跟誰去?",
    "若發生地震你要逃跑只能拿一樣東西，你會拿什麼?",
    "你認為在哪跨年最浪漫?",
    "要選另一半，眼睛是要深遂的好．還是小眼睛好?",
    "愛情跟麵包，你會選哪一個?",
    "你醒來發現旁邊睡了一個陌生人，你會怎麼辦?",
    "如果你會功夫，你想要什麼功夫?",
    "提到劉德華，你會馬上想到什麼?",
    "最經典的西洋電影，你會推薦哪一部?",
    "你最喜歡和哪一個星座的人當朋友?",
    "當老闆對你說你明天可以不要來了，你會怎麼反應?",
    "最近一次去的遊樂園是哪一個?",
    "如果要跟一個人說對不起，你想對誰說?",
    "四個季節你最喜歡哪一個?",
    "提到NBA，你會想到哪個球星?",
    "要選台灣離島深度旅行，你會選哪裡?",
    "露營帳篷和露營車，你會選哪個住?",
    "夜釣小管和夜遊看梅花鹿，你會選哪個?",
    "當你另一半必須要有的一個特點?",
    "最喜歡的便利商店飲料?",
    "上廁所上到一半，老闆打來你會怎麼辦?",
    "最喜歡的夜市小吃?",
    "最近聽到的笑話?",
    "最喜歡的一句話(至理名言)?",
    "如果有下輩子，想當男生還是女生?",
    "回憶國小時期，現在還有印象的事是什麼?",
    "宏正上班第一天，最有印象的事?",
    "最喜歡的卡通人物?",
    "做過最有勇氣的事?",
    "扶老太太過馬路和淨灘，哪一件事你覺得比較有意義?",
    "聽到哪一句話，你會馬上翻臉?",
    "當你不爽的時候，會怎麼樣?",
    "看農民曆你會先看什麼資訊?",
    "你喜歡過聖誕節還是中秋節?",
    "你喜歡戴墨鏡還是戴帽子?",
    "彩虹七個顏色，你會喜歡哪一色?",
    "海水浴場和動物園，你比較喜歡哪一個?",
    "如果可以改變，你想多高(身高)?",
    "你退休後會想在哪個城市居住?",
    "珍珠和椰果，你比較喜歡飲料加哪種料?",
    "最推薦的飲料店?",
    "解封後，你最想做的事是什麼?",
    "林志玲和侯佩岑，你覺得誰比較是你的菜?",
    "給你抱怨公司一件事，你會講什麼?",
    "當你和老闆獨處在電梯，從1樓搭到14樓的期間，你會講什麼話?",
    "近期發生你最後悔的事?",
];

var Qlist_0s = [Qlist_0_00, Qlist_0_01, Qlist_0_02, Qlist_0_03, Qlist_0_04]